export enum AnimalType {
  SAPI = 'SAPI',
  KAMBING = 'KAMBING',
  DOMBA = 'DOMBA',
  SAPI_KOLEKTIF = 'SAPI_KOLEKTIF',
  SAPI_KOLEKTIF_A = 'SAPI_KOLEKTIF_A',
  SAPI_KOLEKTIF_B = 'SAPI_KOLEKTIF_B',
  SAPI_KOLEKTIF_C = 'SAPI_KOLEKTIF_C',
  SAPI_PERORANGAN = 'SAPI_PERORANGAN',
}
